### ISSUE TITLE
Failure to build with GHC 8.6

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/saw-core#30]
There's an abundant use of `fail` without `MonadFail` here (as well as incomplete pattern matches in `do`-notation:
```
src/Verifier/SAW/Recognizer.hs:119:20: error:                                                                                                                
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘GlobalDef i’                                                                                                              
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asGlobalDef :: forall (f :: * -> *).
                                  Monad f =>
                                  Recognizer f Term Ident
        at src/Verifier/SAW/Recognizer.hs:118:1-51
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail f) to the context of                                                                                               
          the type signature for:
            asGlobalDef :: forall (f :: * -> *).
                           Monad f =>
                           Recognizer f Term Ident
    • In a stmt of a 'do' block: GlobalDef i <- asFTermF t
      In the expression:
        do GlobalDef i <- asFTermF t
           return i
      In an equation for ‘asGlobalDef’:
          asGlobalDef t
            = do GlobalDef i <- asFTermF t
                 return i
    |
119 | asGlobalDef t = do GlobalDef i <- asFTermF t; return i
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^

src/Verifier/SAW/Recognizer.hs:217:3: error:                                                                                                                 
    • Could not deduce (Control.Monad.Fail.MonadFail m)                                                                                                      
        arising from a do statement
        with the failable pattern ‘RecordProj u s’                                                                                                           
      from the context: Monad m                                                                                                                              
        bound by the type signature for:                                                                                                                     
                   asRecordSelector :: forall (m :: * -> *).                                                                                                 
                                       Monad m =>
                                       Recognizer m Term (Term, FieldName)
        at src/Verifier/SAW/Recognizer.hs:215:1-68
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail m) to the context of                                                                                               
          the type signature for:
            asRecordSelector :: forall (m :: * -> *).
                                Monad m =>
                                Recognizer m Term (Term, FieldName)                                                                                          
    • In a stmt of a 'do' block: RecordProj u s <- asFTermF t                                                                                                
      In the expression:                                                                                                                                     
        do RecordProj u s <- asFTermF t
           return (u, s)                                                                                                                                     
      In an equation for ‘asRecordSelector’:                                                                                                                 
          asRecordSelector t
            = do RecordProj u s <- asFTermF t                                                                                                                
                 return (u, s)                                                                                                                               
    |
217 |   RecordProj u s <- asFTermF t
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Verifier/SAW/Recognizer.hs:223:21: error:                                                                                                                
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘CtorApp c ps args’                                                                                                        
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asCtorParams :: forall (f :: * -> *).
                                   Monad f =>
                                   Recognizer f Term (Ident, [Term], [Term])
        at src/Verifier/SAW/Recognizer.hs:222:1-70
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail f) to the context of                                                                                               
          the type signature for:
            asCtorParams :: forall (f :: * -> *).
                            Monad f =>
                            Recognizer f Term (Ident, [Term], [Term])                                                                                        
    • In a stmt of a 'do' block: CtorApp c ps args <- asFTermF t                                                                                             
      In the expression:                                                                                                                                     
        do CtorApp c ps args <- asFTermF t                                                                                                                   
           return (c, ps, args)                                                                                                                              
      In an equation for ‘asCtorParams’:                                                                                                                     
          asCtorParams t
            = do CtorApp c ps args <- asFTermF t                                                                                                             
                 return (c, ps, args)                                                                                                                        
    |
223 | asCtorParams t = do CtorApp c ps args <- asFTermF t; return (c,ps,args)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Verifier/SAW/Recognizer.hs:242:15: error:                                                                                                                
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘CtorApp c ps args’                                                                                                        
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asCtor :: forall (f :: * -> *).
                             Monad f =>
                             Recognizer f Term (Ident, [Term])
        at src/Verifier/SAW/Recognizer.hs:241:1-56
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail f) to the context of                                                                                               
          the type signature for:
            asCtor :: forall (f :: * -> *).                                                                                                                  
                      Monad f =>                                                                                                                             
                      Recognizer f Term (Ident, [Term])                                                                                                      
    • In a stmt of a 'do' block: CtorApp c ps args <- asFTermF t                                                                                             
      In the expression:                                                                                                                                     
        do CtorApp c ps args <- asFTermF t                                                                                                                   
           return (c, ps ++ args)                                                                                                                            
      In an equation for ‘asCtor’:                                                                                                                           
          asCtor t
            = do CtorApp c ps args <- asFTermF t                                                                                                             
                 return (c, ps ++ args)                                                                                                                      
    |
242 | asCtor t = do CtorApp c ps args <- asFTermF t; return (c,ps ++ args)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Verifier/SAW/Recognizer.hs:246:25: error:                                                                                                                
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘DataTypeApp c ps args’                                                                                                    
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asDataTypeParams :: forall (f :: * -> *).
                                       Monad f =>
                                       Recognizer f Term (Ident, [Term], [Term])
        at src/Verifier/SAW/Recognizer.hs:245:1-74
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail f) to the context of                                                                                               
          the type signature for:
            asDataTypeParams :: forall (f :: * -> *).
                                Monad f =>
                                Recognizer f Term (Ident, [Term], [Term])                                                                                    
    • In a stmt of a 'do' block: DataTypeApp c ps args <- asFTermF t                                                                                         
      In the expression:                                                                                                                                     
        do DataTypeApp c ps args <- asFTermF t                                                                                                               
           return (c, ps, args)                                                                                                                              
      In an equation for ‘asDataTypeParams’:                                                                                                                 
          asDataTypeParams t                                                                                                                                 
            = do DataTypeApp c ps args <- asFTermF t
                 return (c, ps, args)
    |
246 | asDataTypeParams t = do DataTypeApp c ps args <- asFTermF t; return (c,ps,args)
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                                                                                             
src/Verifier/SAW/Recognizer.hs:250:19: error:                                                                                                                
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘DataTypeApp c ps args’                                                                                                    
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asDataType :: forall (f :: * -> *).
                                 Monad f =>
                                 Recognizer f Term (Ident, [Term])
        at src/Verifier/SAW/Recognizer.hs:249:1-60
      Possible fix:                                                                                                                                          
        add (Control.Monad.Fail.MonadFail f) to the context of                                                                                               
          the type signature for:
            asDataType :: forall (f :: * -> *).
                          Monad f =>
                          Recognizer f Term (Ident, [Term])                                                                                                  
    • In a stmt of a 'do' block: DataTypeApp c ps args <- asFTermF t                                                                                         
      In the expression:                                                                                                                                     
        do DataTypeApp c ps args <- asFTermF t                                                                                                               
           return (c, ps ++ args)                                                                                                                            
      In an equation for ‘asDataType’:                                                                                                                       
          asDataType t
            = do DataTypeApp c ps args <- asFTermF t                                                                                                         
                 return (c, ps ++ args)                                                                                                                      
    |
250 | asDataType t = do DataTypeApp c ps args <- asFTermF t; return (c,ps ++ args)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                                                                                             
src/Verifier/SAW/Recognizer.hs:255:6: error:                                                                                                                 
    • Could not deduce (Control.Monad.Fail.MonadFail f)                                                                                                      
        arising from a do statement
        with the failable pattern ‘RecursorApp d
                                               params
                                               p_ret
                                               cs_fs
                                               ixs
                                               arg’                                                                                                          
      from the context: Monad f                                                                                                                              
        bound by the type signature for:
                   asRecursorApp :: forall (f :: * -> *).
                                    Monad f =>
                                    Recognizer
                                      f Term (Ident, [Term], Term, [(Ident, Term)], [Term], Term)
        at src/Verifier/SAW/Recognizer.hs:(252,1)-(253,74)
      Possible fix:
        add (Control.Monad.Fail.MonadFail f) to the context of
          the type signature for:
            asRecursorApp :: forall (f :: * -> *).
                             Monad f =>
                             Recognizer                                                                                                                      
                               f Term (Ident, [Term], Term, [(Ident, Term)], [Term], Term)                                                                   
    • In a stmt of a 'do' block:                                                                                                                             
        RecursorApp d params p_ret cs_fs ixs arg <- asFTermF t                                                                                               
      In the expression:                                                                                                                                     
        do RecursorApp d params p_ret cs_fs ixs arg <- asFTermF t                                                                                            
           return (d, params, p_ret, cs_fs, ixs, arg)                                                                                                        
      In an equation for ‘asRecursorApp’:                                                                                                                    
          asRecursorApp t                                                                                                                                    
            = do RecursorApp d params p_ret cs_fs ixs arg <- asFTermF t                                                                                      
                 return (d, params, p_ret, cs_fs, ixs, arg)
    |
255 |   do RecursorApp d params p_ret cs_fs ixs arg <- asFTermF t;
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Verifier/SAW/Recognizer.hs:270:20: error:
    • Could not deduce (Control.Monad.Fail.MonadFail f)
        arising from a do statement
        with the failable pattern ‘StringLit i’
      from the context: Monad f
        bound by the type signature for:
                   asStringLit :: forall (f :: * -> *).
                                  Monad f =>
                                  Recognizer f Term String
        at src/Verifier/SAW/Recognizer.hs:269:1-52
      Possible fix:
        add (Control.Monad.Fail.MonadFail f) to the context of
          the type signature for:
            asStringLit :: forall (f :: * -> *).
                           Monad f =>
                           Recognizer f Term String
    • In a stmt of a 'do' block: StringLit i <- asFTermF t
      In the expression:
        do StringLit i <- asFTermF t
           return i
      In an equation for ‘asStringLit’:
          asStringLit t
            = do StringLit i <- asFTermF t
                 return i
    |
270 | asStringLit t = do StringLit i <- asFTermF t; return i
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by brianhuffman** [comment]
Yes, all those operations in `Recognizer` should have a `MonadFail` constraint. I believe that they were originally all specific to the `Maybe` monad, but then they were generalized for convenience.

**Comment by siddharthist** [comment]
Closed via #32
